# Generated by Django 2.2.1 on 2019-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0002_auto_20190522_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmonblog',
            name='ability',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='intro',
            field=models.CharField(default='placeholder', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='move_four',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='move_one',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='move_three',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='move_two',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='nature',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pokemon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='spAtk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='spDef',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='type_one',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='type_two',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bmonblog',
            name='par_one',
            field=models.CharField(max_length=10000),
        ),
    ]
