# Generated by Django 2.2.1 on 2019-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0003_auto_20190522_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmonblog',
            name='par_one',
            field=models.TextField(max_length=10000),
        ),
    ]
