# Generated by Django 2.2.1 on 2019-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0004_auto_20190522_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmonblog',
            name='intro',
            field=models.TextField(max_length=10000),
        ),
    ]
