# Generated by Django 2.2.1 on 2019-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0006_auto_20190524_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmonblog',
            name='pokemon',
            field=models.CharField(blank=True, default='/static/brokemon/images/sprites/Venusaur.png', max_length=100),
        ),
    ]
