# Generated by Django 2.2.1 on 2019-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0007_auto_20190524_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmonblog',
            name='pokemon',
        ),
        migrations.AlterField(
            model_name='bmonblog',
            name='type_one',
            field=models.CharField(default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='bmonblog',
            name='type_two',
            field=models.CharField(default='NON', max_length=3),
        ),
    ]
