# Generated by Django 2.2.1 on 2019-05-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0008_auto_20190525_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmonblog',
            name='ability',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='bmonblog',
            name='type_one',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water'), ('None', 'None')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bmonblog',
            name='type_two',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water'), ('None', 'None')], max_length=15),
        ),
    ]
