# Generated by Django 2.2.1 on 2019-05-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0009_auto_20190525_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmonblog',
            name='pic_five',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='pic_four',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='pic_three',
        ),
    ]
