# Generated by Django 2.2.1 on 2019-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0010_auto_20190525_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmonblog',
            name='item',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
