# Generated by Django 2.2.1 on 2019-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0011_bmonblog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmonblog',
            name='nickname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
