# Generated by Django 2.2.1 on 2019-05-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0013_auto_20190531_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmonblog',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_eight',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_five',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_four',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_nine',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_one',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_seven',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_six',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_ten',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_three',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='par_two',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_eight',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_five',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_four',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_intro',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_nine',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_one',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_seven',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_six',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_ten',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_three',
        ),
        migrations.RemoveField(
            model_name='bmonblog',
            name='title_two',
        ),
    ]
