# Generated by Django 2.2.1 on 2019-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0015_auto_20190531_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmonblog',
            name='pic_eight',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_five',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_four',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_nine',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_seven',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_six',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_ten',
            field=models.CharField(blank=True, max_length=115),
        ),
        migrations.AddField(
            model_name='bmonblog',
            name='pic_three',
            field=models.CharField(blank=True, max_length=115),
        ),
    ]
