# Generated by Django 2.2.1 on 2019-05-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokemon', '0016_auto_20190531_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmonblog',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
